import type { Metadata } from "next";
import { ThemeProvider } from "@/app/components/theme-provider";

// Static
import localFont from "next/font/local";
import "./globals.css";

// Components
import { Toaster } from "@/components/ui/sonner"


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Heracles",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <Toaster />
        <div className="flex flex-col">
          {/* <NavbarComponent /> */}
          {children}
          {/* <FooterComponent /> */}
        </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
