import type { Metadata } from "next";

// Static
import localFont from "next/font/local";
import "./globals.css";

// Components
import ToastComponent from "@/app/components/toast/ToastComponent";

// Icons
import CookieIcon from "@/app/components/icons/CookieIcon";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Heracles",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastComponent
          title="Votre vie privée est importante."
          message={`Nous utilisons des cookies pour améliorer votre expérience de navigation et analyser notre trafic. En continuant votre navigation sur le site, vous consentez à l'utilisation de cookies.`}
          type="default"
          duration={10000}
          icon={<CookieIcon width={24} height={24} className="fill-gray-900" />}
        />
        <div className="flex flex-col">
          {/* <NavbarComponent /> */}
          {children}
          {/* <FooterComponent /> */}
        </div>
      </body>
    </html>
  );
}
