# Use the official Node.js image
FROM node:18-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Next.js project files into the container
COPY ./frontend/package.json ./frontend/package-lock.json /app/

# Install dependencies
RUN npm install

# Copy the rest of the Next.js project files
COPY ./frontend /app

# Expose port 3000 for Next.js
EXPOSE 3000

# Start the Next.js development server
CMD ["npm", "run", "dev", "--host"]
