import type { Metadata } from "next";

// Components
import NavbarComponent from "@/app/components/navbar/NavbarComponent";
import SidebarComponent from "@/app/components/sidebar/SidebarComponent";
import FooterApp from "@/app/components/footer/FooterApp";

export const metadata: Metadata = {
  title: "Heracles",
  description: "Generated by create next app",
};

export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <div className="flex flex-col">
      <NavbarComponent />
      <div className="relative h-[calc(100vh-5rem)] flex grow p-2">
        <SidebarComponent />
        <div className="grow rounded bg-gray-50 shadow p-2">
          {children}
        </div>
      </div>
      <FooterApp />
    </div>
  );
}
