name: Deploy heracles to EC2

on:
  push:
    branches:
      - preprod  # Or whatever branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH keys
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      # Test SSH connection
      - name: Test SSH connection
        run: |
          echo "EC2_USER: $EC2_USER"
          echo "EC2_HOST: $EC2_HOST"
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "echo Connected!"
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      # Install dependencies (if needed)
      - name: Install dependencies on the server
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "
            cd /srv/heracles && \
            git pull origin main && \
            source ./venv/bin/activate && \
            pip install -r requirements.txt && \
            sudo systemctl restart heracles_api
          "
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}

      # (Optional) Deploy static files or handle specific tasks

