name: Frontend Unit Tests

on:
  push:
    branches:
      - main
      - preprod
      - prod

  pull_request:

jobs:
  test:
    name: Frontend Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci --force
        working-directory: frontend

      - name: Run Unit Tests (Vitest)
        run: npm run test:unit
        working-directory: frontend

