name: Frontend e2e Tests

on:
  push:
    branches:
      - main
      - preprod
      - prod

  pull_request:

jobs:
  test:
    name: Frontend e2e Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          npm ci --force
          npx playwright install --with-deps --force  
        working-directory: frontend

      - name: Start the frontend application
        run: npm run dev &
        working-directory: frontend
        env:
          NODE_ENV: test
      
      - name: Wait for frontend to be ready
        run: npx wait-on http://localhost:3000
        working-directory: frontend

      - name: Run e2e Tests (Playwright)
        run: npm run e2e
        working-directory: frontend

